---
- block:
    - name: Install aminvakil.mysql_initial role from ansible-galaxy
      command: ansible-galaxy install aminvakil.mysql_initial
      register: result
      changed_when: '"already installed" not in result.stderr'
      become: false
      delegate_to: localhost

    - name: Install mysql
      include_role:
        name: aminvakil.mysql_initial
  when: mysql_initial | bool

- name: Check if mysql is installed or not
  command: ls /etc/mysql
  register: result
  changed_when: false
  ignore_errors: true

- name: Fail when mysql has not been installed
  assert:
    that:
      - result.rc == 0
      - '"No such" not in result.stdout'
    fail_msg: MySQL has not been installed, use aminvakil.mysql_initial to install MySQL first.
